version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - ENVIRONMENT=production
      - JWT_SECRET=${JWT_SECRET}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - DB_POOL_SIZE=20
      - DB_POOL_TIMEOUT=30
      - HTTP_TIMEOUT=60
      - ENABLE_CACHE=true
      - CACHE_TTL=600
      - LOG_LEVEL=INFO
      - MAX_UPLOAD_SIZE=100000000
      - DEFAULT_LANGUAGE=fr
      - SPEAKER_LABELS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./uploads:/var/www/uploads
    depends_on:
      - api
